server:
  port: 9000

spring:
  application:
    name: basis-zuul
  datasource:
    url: jdbc:mysql://localhost:3306/test?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver


# 与Eureka集成
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    # 是否从eureka取服务
    fetch-registry: true
    # 是否注册到eureka
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registryFetchIntervalSeconds: 3
    leaseRenewalIntervalInSeconds: 3

# Zuul路由配置
zuul:
  retryable: true
  prefix:  /jokeshop
  routes:
    msa-account: /account/**
    msa-order: /order/**
    msa-goods: /goods/**
  sensitiveHeaders: Cookie,Set-Cookie
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000


# log级别控制
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.albusxing: INFO

# 暴露端点
management:
  endpoints:
    web:
      exposure:
        include: "*"