spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
      config:
        file-extension: yaml
        server-addr: 127.0.0.1:8848