
server:
  # 服务端口
  port: 8010

spring:
  application:
    # 应用名称
    name: msa-account
  profiles:
    active: dev

### Eureka配置
eureka:
  # eureka实例相关的配置
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    # 租约超时时间间隔，秒
    lease-expiration-duration-in-seconds: 90
    # 发送心跳时间间隔，秒
    lease-renewal-interval-in-seconds: 30
    metadata-map:
      developer: albusxing
  # eureka客户端相关的配置
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    # 开启健康检查
    healthcheck:
      enabled: true
    # 是否启用eureka
    enabled: true
    # 服务抓取时间间隔
    registry-fetch-interval-seconds: 30


# 日志级别配置
logging:
  level:
    com.albusxing.msa: INFO

# 暴露端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
