################### eureka 集群启动 ###################

server:
  # 服务端口
  port: 8762

spring:
  application:
    # 应用名称
    name: basis-eureka


eureka:
  # eureka实例相关的配置
  instance:
    # 指定eureka实例的主机名称。可以用来区分集群环境下，不同实例的主机名称
    hostname: localhost
  # eureka客户端相关的配置
  client:
    # 是否从eureka取服务
    fetch-registry: true
    # 是否注册到eureka
    register-with-eureka: true
    service-url:
      defaultZone: https://localhost:8761/eureka
  # eureka服务端相关的配置
  server:
    # 是否启用自我保护模式
    enable-self-preservation: false
    wait-time-in-ms-when-sync-empty: 0
    # 移除失效服务的间隔时间，单位毫秒
    eviction-interval-timer-in-ms: 5000

# 日志级别
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.albusxing: INFO
